package cn.bytecloud.iot.eoms.instance.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of t_disk_stats.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DiskStats implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private String id;

	/** s_service_name. */
	private String serviceName;

	/** i_disk_value. */
	private Integer diskValue;

	/** is_alarmed. */
	private Integer isAlarmed;

	/** d_create_time. */
	private Date createTime;

	/** d_update_time. */
	private Date updateTime;

	/**
	 * Constructor.
	 */
	public DiskStats() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the is_alarmed.
	 * 
	 * @param isAlarmed
	 *            is_alarmed
	 */
	public void setIsAlarmed(Integer isAlarmed) {
		this.isAlarmed = isAlarmed;
	}

	/**
	 * Get the is_alarmed.
	 * 
	 * @return is_alarmed
	 */
	public Integer getIsAlarmed() {
		return this.isAlarmed;
	}

	

	public String getServiceName() {
		return serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public Integer getDiskValue() {
		return diskValue;
	}

	public void setDiskValue(Integer diskValue) {
		this.diskValue = diskValue;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		DiskStats other = (DiskStats) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
