package cn.bytecloud.iot.eoms.instance.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of t_threshold.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Threshold implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private String id;

	/** i_threshold_type. */
	private Integer thresholdType;

	/** i_threshold_value. */
	private Integer thresholdValue;

	/** d_create_time. */
	private Date createTime;

	/** d_update_time. */
	private Date updateTime;

	/** is_delete. */
	private Integer isDelete;

	/**
	 * Constructor.
	 */
	public Threshold() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	public Integer getThresholdType() {
		return thresholdType;
	}

	public void setThresholdType(Integer thresholdType) {
		this.thresholdType = thresholdType;
	}

	public Integer getThresholdValue() {
		return thresholdValue;
	}

	public void setThresholdValue(Integer thresholdValue) {
		this.thresholdValue = thresholdValue;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * Set the is_delete.
	 * 
	 * @param isDelete
	 *            is_delete
	 */
	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}

	/**
	 * Get the is_delete.
	 * 
	 * @return is_delete
	 */
	public Integer getIsDelete() {
		return this.isDelete;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Threshold other = (Threshold) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
