package com.changhong.iot.config.configfile.entity;

import com.changhong.iot.config.config.CustomDateSerializer;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Data;
import org.springframework.data.annotation.Id;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of t_config_files.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
public class ConfigFiles implements Serializable {

	/** id. */
	@Id
	private String id;

	/** s_service_name. */
	private String serviceName;

	/** s_config_file. */
	private String configFile;
	
	/** d_create_time. */
	@JsonSerialize(using = CustomDateSerializer.class)
	private Date createTime;

	/** d_update_time. */

	@JsonSerialize(using = CustomDateSerializer.class)
	private Date updateTime;

	/** is_delete. */

	private Integer isDelete;

}
